# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import apthunter_pb2 as apthunter__pb2


class WriterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateOrUpdate = channel.unary_unary(
        '/pb.Writer/CreateOrUpdate',
        request_serializer=apthunter__pb2.CreateOrUpdateRequest.SerializeToString,
        response_deserializer=apthunter__pb2.CreateOrUpdateResponse.FromString,
        )


class WriterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateOrUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WriterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateOrUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOrUpdate,
          request_deserializer=apthunter__pb2.CreateOrUpdateRequest.FromString,
          response_serializer=apthunter__pb2.CreateOrUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.Writer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
