# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apthunter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='apthunter.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x61pthunter.proto\x12\x02pb\"#\n\x15\x43reateOrUpdateRequest\x12\n\n\x02id\x18\n \x01(\t\"\x18\n\x16\x43reateOrUpdateResponse2S\n\x06Writer\x12I\n\x0e\x43reateOrUpdate\x12\x19.pb.CreateOrUpdateRequest\x1a\x1a.pb.CreateOrUpdateResponse\"\x00\x62\x06proto3')
)




_CREATEORUPDATEREQUEST = _descriptor.Descriptor(
  name='CreateOrUpdateRequest',
  full_name='pb.CreateOrUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.CreateOrUpdateRequest.id', index=0,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=58,
)


_CREATEORUPDATERESPONSE = _descriptor.Descriptor(
  name='CreateOrUpdateResponse',
  full_name='pb.CreateOrUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['CreateOrUpdateRequest'] = _CREATEORUPDATEREQUEST
DESCRIPTOR.message_types_by_name['CreateOrUpdateResponse'] = _CREATEORUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateOrUpdateRequest = _reflection.GeneratedProtocolMessageType('CreateOrUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEORUPDATEREQUEST,
  __module__ = 'apthunter_pb2'
  # @@protoc_insertion_point(class_scope:pb.CreateOrUpdateRequest)
  ))
_sym_db.RegisterMessage(CreateOrUpdateRequest)

CreateOrUpdateResponse = _reflection.GeneratedProtocolMessageType('CreateOrUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEORUPDATERESPONSE,
  __module__ = 'apthunter_pb2'
  # @@protoc_insertion_point(class_scope:pb.CreateOrUpdateResponse)
  ))
_sym_db.RegisterMessage(CreateOrUpdateResponse)



_WRITER = _descriptor.ServiceDescriptor(
  name='Writer',
  full_name='pb.Writer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOrUpdate',
    full_name='pb.Writer.CreateOrUpdate',
    index=0,
    containing_service=None,
    input_type=_CREATEORUPDATEREQUEST,
    output_type=_CREATEORUPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WRITER)

DESCRIPTOR.services_by_name['Writer'] = _WRITER

# @@protoc_insertion_point(module_scope)
