// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apartment.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Id                   string   `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de0becdee01dfe4, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Id                   string   `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,20,opt,name=address,proto3" json:"address,omitempty"`
	Url                  string   `protobuf:"bytes,30,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,40,opt,name=title,proto3" json:"title,omitempty"`
	Price                float32  `protobuf:"fixed32,50,opt,name=price,proto3" json:"price,omitempty"`
	Bedrooms             uint64   `protobuf:"varint,60,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms            float32  `protobuf:"fixed32,70,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	Sqft                 float32  `protobuf:"fixed32,80,opt,name=sqft,proto3" json:"sqft,omitempty"`
	AvailableDate        string   `protobuf:"bytes,90,opt,name=available_date,json=availableDate,proto3" json:"available_date,omitempty"`
	Cats                 bool     `protobuf:"varint,100,opt,name=cats,proto3" json:"cats,omitempty"`
	Dogs                 bool     `protobuf:"varint,110,opt,name=dogs,proto3" json:"dogs,omitempty"`
	HousingType          string   `protobuf:"bytes,120,opt,name=housing_type,json=housingType,proto3" json:"housing_type,omitempty"`
	WdType               string   `protobuf:"bytes,130,opt,name=wd_type,json=wdType,proto3" json:"wd_type,omitempty"`
	ParkingType          string   `protobuf:"bytes,140,opt,name=parking_type,json=parkingType,proto3" json:"parking_type,omitempty"`
	Images               []string `protobuf:"bytes,150,rep,name=images,proto3" json:"images,omitempty"`
	Body                 string   `protobuf:"bytes,160,opt,name=body,proto3" json:"body,omitempty"`
	Lng                  float32  `protobuf:"fixed32,170,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  float32  `protobuf:"fixed32,180,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5de0becdee01dfe4, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetResponse) GetBedrooms() uint64 {
	if m != nil {
		return m.Bedrooms
	}
	return 0
}

func (m *GetResponse) GetBathrooms() float32 {
	if m != nil {
		return m.Bathrooms
	}
	return 0
}

func (m *GetResponse) GetSqft() float32 {
	if m != nil {
		return m.Sqft
	}
	return 0
}

func (m *GetResponse) GetAvailableDate() string {
	if m != nil {
		return m.AvailableDate
	}
	return ""
}

func (m *GetResponse) GetCats() bool {
	if m != nil {
		return m.Cats
	}
	return false
}

func (m *GetResponse) GetDogs() bool {
	if m != nil {
		return m.Dogs
	}
	return false
}

func (m *GetResponse) GetHousingType() string {
	if m != nil {
		return m.HousingType
	}
	return ""
}

func (m *GetResponse) GetWdType() string {
	if m != nil {
		return m.WdType
	}
	return ""
}

func (m *GetResponse) GetParkingType() string {
	if m != nil {
		return m.ParkingType
	}
	return ""
}

func (m *GetResponse) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *GetResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetResponse) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *GetResponse) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
}

func init() { proto.RegisterFile("apartment.proto", fileDescriptor_5de0becdee01dfe4) }

var fileDescriptor_5de0becdee01dfe4 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xb1, 0x8f, 0xd3, 0x30,
	0x14, 0xc6, 0x49, 0x52, 0xca, 0xf5, 0xf5, 0xe8, 0x81, 0x39, 0x89, 0xa7, 0xd3, 0x09, 0x85, 0x48,
	0x48, 0x99, 0x3a, 0x1c, 0x62, 0x63, 0x41, 0x42, 0xdc, 0x8a, 0x22, 0x26, 0x96, 0x93, 0x73, 0x7e,
	0xe4, 0x22, 0xd2, 0xd8, 0x8d, 0x5f, 0x29, 0x5d, 0x99, 0x99, 0x99, 0x99, 0x99, 0xf9, 0x1f, 0xf8,
	0xb7, 0x90, 0x9f, 0xdb, 0x54, 0xba, 0xed, 0xfb, 0x7e, 0x9f, 0x3f, 0xcb, 0xf6, 0x33, 0x9c, 0x69,
	0xa7, 0x07, 0x5e, 0x51, 0xcf, 0x4b, 0x37, 0x58, 0xb6, 0x2a, 0x75, 0x75, 0x71, 0x09, 0x70, 0x4d,
	0x5c, 0xd1, 0x7a, 0x43, 0x9e, 0xd5, 0x02, 0xd2, 0xd6, 0x20, 0xe4, 0x49, 0x39, 0xab, 0xd2, 0xd6,
	0x14, 0xff, 0x32, 0x98, 0x4b, 0xec, 0x9d, 0xed, 0x3d, 0xdd, 0xcf, 0x15, 0xc2, 0x23, 0x6d, 0xcc,
	0x40, 0xde, 0xe3, 0xb9, 0xc0, 0x83, 0x55, 0x4f, 0x20, 0xdb, 0x0c, 0x1d, 0xbe, 0x10, 0x1a, 0xa4,
	0x3a, 0x87, 0x87, 0xdc, 0x72, 0x47, 0x58, 0x0a, 0x8b, 0x26, 0x50, 0x37, 0xb4, 0xb7, 0x84, 0x57,
	0x79, 0x52, 0xa6, 0x55, 0x34, 0xea, 0x02, 0x4e, 0x6a, 0x32, 0x83, 0xb5, 0x2b, 0x8f, 0x6f, 0xf3,
	0xa4, 0x9c, 0x54, 0xa3, 0x57, 0x97, 0x30, 0xab, 0x35, 0xdf, 0xc5, 0xf0, 0x83, 0xb4, 0x8e, 0x40,
	0x29, 0x98, 0xf8, 0xf5, 0x17, 0xc6, 0x8f, 0x12, 0x88, 0x56, 0xaf, 0x60, 0xa1, 0xbf, 0xe9, 0xb6,
	0xd3, 0x75, 0x47, 0x37, 0x46, 0x33, 0xe1, 0x67, 0x39, 0xc2, 0xe3, 0x91, 0xbe, 0xd7, 0x4c, 0xa1,
	0x7a, 0xab, 0xd9, 0xa3, 0xc9, 0x93, 0xf2, 0xa4, 0x12, 0x1d, 0x98, 0xb1, 0x8d, 0xc7, 0x3e, 0xb2,
	0xa0, 0xd5, 0x4b, 0x38, 0xbd, 0xb3, 0x1b, 0xdf, 0xf6, 0xcd, 0x0d, 0xef, 0x1c, 0xe1, 0x77, 0xd9,
	0x6c, 0xbe, 0x67, 0x9f, 0x76, 0x8e, 0xc2, 0xbb, 0x6c, 0x4d, 0x4c, 0x7f, 0x24, 0x12, 0x4f, 0xb7,
	0x46, 0x92, 0x02, 0x4e, 0x9d, 0x1e, 0xbe, 0x8e, 0xe5, 0x9f, 0x31, 0x9e, 0xef, 0xa1, 0xac, 0x79,
	0x0e, 0xd3, 0x76, 0xa5, 0x1b, 0xf2, 0xf8, 0x2b, 0xc9, 0xb3, 0x50, 0x8e, 0x56, 0x3d, 0x83, 0x49,
	0x6d, 0xcd, 0x0e, 0x7f, 0xc7, 0x92, 0x18, 0xf5, 0x14, 0xb2, 0xae, 0x6f, 0xf0, 0x4f, 0x22, 0x37,
	0x0e, 0x5a, 0x90, 0x66, 0xfc, 0x7b, 0x40, 0x9a, 0xaf, 0xde, 0xc0, 0xec, 0xdd, 0x61, 0xfc, 0xaa,
	0x84, 0xec, 0x9a, 0x58, 0x2d, 0x96, 0xae, 0x5e, 0x1e, 0xa7, 0x7f, 0x71, 0x36, 0xfa, 0x38, 0xee,
	0xe2, 0x41, 0x3d, 0x95, 0x9f, 0xf2, 0xfa, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0xf1, 0x54,
	0xd4, 0x3c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApartmentClient is the client API for Apartment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApartmentClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type apartmentClient struct {
	cc *grpc.ClientConn
}

func NewApartmentClient(cc *grpc.ClientConn) ApartmentClient {
	return &apartmentClient{cc}
}

func (c *apartmentClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/pb.Apartment/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApartmentServer is the server API for Apartment service.
type ApartmentServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterApartmentServer(s *grpc.Server, srv ApartmentServer) {
	s.RegisterService(&_Apartment_serviceDesc, srv)
}

func _Apartment_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Apartment/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Apartment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Apartment",
	HandlerType: (*ApartmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Apartment_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apartment.proto",
}
