// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apthunter.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateOrUpdateRequest struct {
	Id                   string   `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateRequest) Reset()         { *m = CreateOrUpdateRequest{} }
func (m *CreateOrUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateRequest) ProtoMessage()    {}
func (*CreateOrUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_apthunter_917f418df9af38da, []int{0}
}
func (m *CreateOrUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateRequest.Unmarshal(m, b)
}
func (m *CreateOrUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateRequest.Merge(dst, src)
}
func (m *CreateOrUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateRequest.Size(m)
}
func (m *CreateOrUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateRequest proto.InternalMessageInfo

func (m *CreateOrUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateOrUpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateResponse) Reset()         { *m = CreateOrUpdateResponse{} }
func (m *CreateOrUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateResponse) ProtoMessage()    {}
func (*CreateOrUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_apthunter_917f418df9af38da, []int{1}
}
func (m *CreateOrUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateResponse.Unmarshal(m, b)
}
func (m *CreateOrUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateResponse.Merge(dst, src)
}
func (m *CreateOrUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateResponse.Size(m)
}
func (m *CreateOrUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateOrUpdateRequest)(nil), "pb.CreateOrUpdateRequest")
	proto.RegisterType((*CreateOrUpdateResponse)(nil), "pb.CreateOrUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WriterClient is the client API for Writer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WriterClient interface {
	CreateOrUpdate(ctx context.Context, in *CreateOrUpdateRequest, opts ...grpc.CallOption) (*CreateOrUpdateResponse, error)
}

type writerClient struct {
	cc *grpc.ClientConn
}

func NewWriterClient(cc *grpc.ClientConn) WriterClient {
	return &writerClient{cc}
}

func (c *writerClient) CreateOrUpdate(ctx context.Context, in *CreateOrUpdateRequest, opts ...grpc.CallOption) (*CreateOrUpdateResponse, error) {
	out := new(CreateOrUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.Writer/CreateOrUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriterServer is the server API for Writer service.
type WriterServer interface {
	CreateOrUpdate(context.Context, *CreateOrUpdateRequest) (*CreateOrUpdateResponse, error)
}

func RegisterWriterServer(s *grpc.Server, srv WriterServer) {
	s.RegisterService(&_Writer_serviceDesc, srv)
}

func _Writer_CreateOrUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServer).CreateOrUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Writer/CreateOrUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServer).CreateOrUpdate(ctx, req.(*CreateOrUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Writer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Writer",
	HandlerType: (*WriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdate",
			Handler:    _Writer_CreateOrUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apthunter.proto",
}

func init() { proto.RegisterFile("apthunter.proto", fileDescriptor_apthunter_917f418df9af38da) }

var fileDescriptor_apthunter_917f418df9af38da = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x28, 0xc9,
	0x28, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x52, 0xe7, 0x12, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0xf5, 0x2f, 0x0a, 0x2d, 0x48, 0x49, 0x2c,
	0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0xe0,
	0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0x92, 0xe0, 0x12, 0x43, 0x57, 0x58, 0x5c,
	0x90, 0x9f, 0x57, 0x9c, 0x6a, 0x14, 0xcc, 0xc5, 0x16, 0x5e, 0x94, 0x59, 0x92, 0x5a, 0x24, 0xe4,
	0xc9, 0xc5, 0x87, 0xaa, 0x46, 0x48, 0x52, 0xaf, 0x20, 0x49, 0x0f, 0xab, 0x05, 0x52, 0x52, 0xd8,
	0xa4, 0x20, 0x46, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xd5, 0xc8, 0x33, 0x2c, 0xb5, 0x00, 0x00, 0x00,
}
