// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apthunter.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateOrUpdateRequest struct {
	Id                   string   `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,20,opt,name=url,proto3" json:"url,omitempty"`
	Price                float32  `protobuf:"fixed32,30,opt,name=price,proto3" json:"price,omitempty"`
	Title                string   `protobuf:"bytes,40,opt,name=title,proto3" json:"title,omitempty"`
	Images               []string `protobuf:"bytes,50,rep,name=images,proto3" json:"images,omitempty"`
	Body                 string   `protobuf:"bytes,60,opt,name=body,proto3" json:"body,omitempty"`
	Details              []string `protobuf:"bytes,70,rep,name=details,proto3" json:"details,omitempty"`
	Lng                  float32  `protobuf:"fixed32,80,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  float32  `protobuf:"fixed32,90,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateRequest) Reset()         { *m = CreateOrUpdateRequest{} }
func (m *CreateOrUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateRequest) ProtoMessage()    {}
func (*CreateOrUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_apthunter_ca56b44d2423201d, []int{0}
}
func (m *CreateOrUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateRequest.Unmarshal(m, b)
}
func (m *CreateOrUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateRequest.Merge(dst, src)
}
func (m *CreateOrUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateRequest.Size(m)
}
func (m *CreateOrUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateRequest proto.InternalMessageInfo

func (m *CreateOrUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrUpdateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateOrUpdateRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateOrUpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateOrUpdateRequest) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *CreateOrUpdateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateOrUpdateRequest) GetDetails() []string {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *CreateOrUpdateRequest) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *CreateOrUpdateRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type CreateOrUpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateResponse) Reset()         { *m = CreateOrUpdateResponse{} }
func (m *CreateOrUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateResponse) ProtoMessage()    {}
func (*CreateOrUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_apthunter_ca56b44d2423201d, []int{1}
}
func (m *CreateOrUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateResponse.Unmarshal(m, b)
}
func (m *CreateOrUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateResponse.Merge(dst, src)
}
func (m *CreateOrUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateResponse.Size(m)
}
func (m *CreateOrUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateOrUpdateRequest)(nil), "pb.CreateOrUpdateRequest")
	proto.RegisterType((*CreateOrUpdateResponse)(nil), "pb.CreateOrUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WriterClient is the client API for Writer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WriterClient interface {
	CreateOrUpdate(ctx context.Context, in *CreateOrUpdateRequest, opts ...grpc.CallOption) (*CreateOrUpdateResponse, error)
}

type writerClient struct {
	cc *grpc.ClientConn
}

func NewWriterClient(cc *grpc.ClientConn) WriterClient {
	return &writerClient{cc}
}

func (c *writerClient) CreateOrUpdate(ctx context.Context, in *CreateOrUpdateRequest, opts ...grpc.CallOption) (*CreateOrUpdateResponse, error) {
	out := new(CreateOrUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.Writer/CreateOrUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriterServer is the server API for Writer service.
type WriterServer interface {
	CreateOrUpdate(context.Context, *CreateOrUpdateRequest) (*CreateOrUpdateResponse, error)
}

func RegisterWriterServer(s *grpc.Server, srv WriterServer) {
	s.RegisterService(&_Writer_serviceDesc, srv)
}

func _Writer_CreateOrUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServer).CreateOrUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Writer/CreateOrUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServer).CreateOrUpdate(ctx, req.(*CreateOrUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Writer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Writer",
	HandlerType: (*WriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdate",
			Handler:    _Writer_CreateOrUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apthunter.proto",
}

func init() { proto.RegisterFile("apthunter.proto", fileDescriptor_apthunter_ca56b44d2423201d) }

var fileDescriptor_apthunter_ca56b44d2423201d = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x4d, 0x4e, 0x23, 0x37, 0xc5, 0x29, 0xc3, 0x79, 0x8c, 0x57, 0x48, 0x48, 0x95, 0x2a,
	0xc5, 0xd9, 0xda, 0x09, 0x82, 0x95, 0x12, 0x11, 0xc1, 0x6e, 0xe3, 0x0e, 0xe7, 0x42, 0x4c, 0xd6,
	0xdd, 0x49, 0xe1, 0x53, 0xfa, 0x4a, 0x92, 0xc9, 0x59, 0x28, 0xe9, 0xfe, 0xff, 0xdb, 0x8f, 0xdd,
	0x9d, 0x81, 0x33, 0xe3, 0xe5, 0x7d, 0xe8, 0x84, 0x43, 0xe5, 0x43, 0x2f, 0x3d, 0xa6, 0xbe, 0x29,
	0xbe, 0x13, 0xb8, 0xb8, 0x0d, 0x6c, 0x84, 0x1f, 0xc2, 0xb3, 0xb7, 0x46, 0xb8, 0xe6, 0xcf, 0x81,
	0xa3, 0xe0, 0x0a, 0x52, 0x67, 0x09, 0xf2, 0xa4, 0x5c, 0xd6, 0xa9, 0xb3, 0x78, 0x0e, 0x8b, 0x21,
	0xb4, 0xb4, 0x56, 0x30, 0x46, 0x5c, 0xc3, 0x89, 0x0f, 0xee, 0x8d, 0xe9, 0x2a, 0x4f, 0xca, 0xb4,
	0x9e, 0xca, 0x48, 0xc5, 0x49, 0xcb, 0x54, 0xaa, 0x39, 0x15, 0xdc, 0x40, 0xe6, 0x3e, 0xcc, 0x9e,
	0x23, 0xed, 0xf2, 0x45, 0xb9, 0xac, 0x0f, 0x0d, 0x11, 0x8e, 0x9b, 0xde, 0x7e, 0xd1, 0x8d, 0xca,
	0x9a, 0x91, 0xe0, 0xd4, 0xb2, 0x18, 0xd7, 0x46, 0xba, 0x53, 0xf9, 0xb7, 0x8e, 0x7f, 0x68, 0xbb,
	0x3d, 0x3d, 0xea, 0x7b, 0x63, 0x54, 0x62, 0x84, 0x5e, 0x0f, 0xc4, 0x48, 0x41, 0xb0, 0xf9, 0x3f,
	0x50, 0xf4, 0x7d, 0x17, 0x79, 0xf7, 0x04, 0xd9, 0x4b, 0x70, 0xc2, 0x01, 0xef, 0x61, 0xf5, 0xd7,
	0xc1, 0xcb, 0xca, 0x37, 0xd5, 0xec, 0x22, 0xb6, 0xdb, 0xb9, 0xa3, 0xe9, 0xca, 0xe2, 0xa8, 0xc9,
	0x74, 0x97, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x5c, 0x6a, 0xa5, 0x5e, 0x01, 0x00,
	0x00,
}
